---
title: "Project 3: R Package Development and Documentation"
author: "INSERT YOUR NAME(S) HERE"
date: "Due Date Here"
output: html_document
---

You may work with up to one other person for this project. If you would strongly prefer a group of 3 then talk to me to approve your group (for groups of 3 I will add additional requirements to Part 1). If you work in a group and would like to use GitHub for collaboration, see lecture 11 slides 61-64. Using GitHub is not a requirement for this project. 

# Part 1. R Package Development and Documentation (27 points)

## Instructions

For this portion of Project 3, you are being asked to develop a well-documented, well-tested, and well-explained R package.

This R package should include the following functions we've written throughout the class:

* `my_t.test`
* `my_lm`
* `my_knn_cv`

Follow the instruction on Lecture Slides 9 to set up the skeleton of your package. Your package should include the following:

1. (8 points) Complete documentation for each of your functions. Each function must include `@examples` in the documentation. You must add and document the `penguins` data from the `palmerpenguins` package to your own package and export it as the object `my_penguins` (with proper credit in the documentation!).

2. (12 points) A detailed vignette with examples and the use of all of these functions with the penguins data.  Your vignette should start with a paragraph describing the package and what it can be used for (2 points). Specifically, the vignette should have the following parts:

    a. A tutorial for `my_t.test`. First, explain in words the hypothesis that you are testing. You should test a hypothesis about one or more of the variables in the `my_penguins` dataset using `my_t.test`. Then, run the hypothesis test. Interpret the p-value from the t test in context of the data. 
    b. A tutorial for `my_lm` using one variable from the `my_penguins` dataset as a depedent variable and one or more variables from the `my_penguins` dataset as independent variable(s). Carefully interpret the coefficient(s) for the independent variables in your model and interpret the results of the hypothesis test for each coefficient using a p-value cut-off of $\alpha = 0.05$.
    c. A tutorial for `my_knn_cv` using `my_penguins`. Predict output class `species` using covariates `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, and `body_mass_g`. 
    
        * Use $5$-fold cross validation (`k_cv = 5`).
        
        * Iterate from `k_nn`$= 1,\ldots, 10$. For each value of `k_nn`, record the training misclassification rate and the CV misclassification rate (output from your function). Provide a table of this training misclassification rates and CV misclassification rates. 
        
        * State which model you would choose based on the training misclassification rates and which model you would choose based on the CV misclassification rates. Discuss which model you would choose in practice and why.
        
Feel free to look at the vignettes for [lubridate](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html) and [forcats](https://cran.r-project.org/web/packages/forcats/vignettes/forcats.html) for inspiration. 
        
3. (7 points) We will test your package by checking that it can be installed and when `devtools::check()` is run it should return no errors, warnings, or notes.         

### Notes

* Your package directory should be submitted as a .zip file to Canvas.
* All code and documentation should follow the style guidelines outlined in class. As always, be sure to comment your code.


# Part 2. Self-Assessment and Reflection (3 points)

Submit answers to the following questions as a .pdf file to Canvas. A brief paragraph for each will be enough.

1. What was the hardest assignment for you and why? Did you learn anything from the experience? Is there anything you would change about the assignment to help your learning?

2. What are two areas in which you think you did well this quarter? What are two areas in which you could have improved?

3. Is there anything you are glad we covered this quarter? Is there anything you wish had been covered in this course? What programming and computing skills would you like to learn in the future?
