---
title: "Lab 1"
author: "STAT 302"
date: "Due Date Here"
output: html_document
---

<!--- Begin styling code. --->
<style type="text/css">
/* Whole document: */
body{
  font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif;
  font-size: 12pt;
}
h1.title {
  font-size: 38px;
  text-align: center;
}
h4.author {
  font-size: 18px;
  text-align: center;
}
h4.date {
  font-size: 18px;
  text-align: center;
}
</style>
<!--- End styling code. --->

### Collaborators

INSERT NAMES OF ANY STUDENTS WORKED WITH

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions (4 points)

This lab will be worth 20 points, of which 4 can be earned by following instructions. Each item below is worth 1 point.

* Your code should be commented so that it is easy for us to follow.
* Your code should follow the style guidelines from Lecture Slides 1.
* Any reference to code results in text should be done using in-line R code. You should not be typing the actual numbers. Similarly, any values you are asked to calculate must be done using code. They should not be calculated by hand.
* Your document should look nice and be easy to read. Figures should be appropriately sized, headers and subheaders should be used, etc.

When generating data, I recommend viewing and exploring your data to get a sense of what it looks like using both R commands and the Editor tab in RStudio. 
This will help you confirm that what you generated is what you intended. 
It will also give you a sense of what the data look like, which can help decide how you want to present it.

*If you collaborated with anyone, you must include "Collaborated with: FIRSTNAME LASTNAME" at the top of your lab!*

## Part 1. Vectors (8 points)

Let's jump right in and start working with large simulations. You will need the functions `rnorm()` for Normally distributed simulations and `pnorm()` for the percentiles of the Normal distribution. This is all I am going to tell you about these functions, so you will need to use the documentation to help you with these questions! In order to open the documentation (for `rnorm()` for example) go into the console and type `?rnorm()`. 

**1a.** Create and store a vector of 100,000 simulations from a Normal distribution with mean 3 and standard deviation 5 (sometimes written as $N(3, 5^2)$). Print out only the first 5 elements of your vector using `head()`.

**1b.** Generate 4 histograms. The histograms should include the first 50, 500, 5000, and 50000 elements of your simulations, respectively. Be sure to change the title of your histograms to write what they display in plain text. What do you notice about the histograms? Explain why you think this is.

(*Hint: look into the function `hist` to make a histogram and use the parameter `main` to change the title of your histogram*)

**1c.** Compute the mean and standard deviation of your vector from part a. Report them using in-line R code. 

**1d.** In order to standardize vectors, we take each element and subtract the mean and then divide by the standard deviation (computed in part c). Create and store a new vector that is the standardization of your simulations from part (a). Create a histogram for all of these standardized simulations (don't forget to change the title again!). What do you notice?

(*Hint: don't use exactly 3 and 5 for the mean and standard deviation when standardizing. As a sanity check, after you standardize your vector, the mean should be exactly 0!*)

**1f.** Calculate (using an R function, see hint at the start of part 1) the percent of simulations from a $N(0, 1)$ that you *expect* to be above 1.644854. How does this compare to the observed proportion of your standardized simulations that are above 1.644854? 

(*Hint: pay attention to the parameter `lower.tail`. Additionally, to find the proportion of a vector above a certain value, you can use a combination of a logical comparison and the function `mean()`.*)

**1g.** How does the percent of simulations from a $N(0, 1)$ that you *expect* to be above 1.644854 (from part f) compare to the observed proportion of your first **10** standardized simulations that are above 1.644854? Repeat this for your first **100**, **1000**, and **10,000** standardized simulations. 
What do you notice?


## Part 2. Matrices (8 points)

A Binomial distribution with $n$ trials and probability of success $p$, sometimes shorthanded $Bin(n, p)$, represents the number of success out of $n$ independent trials, each with probability of success $p$. 
For this part, we will be using the Binomial distribution equivalent of the functions we used in part 1, specifically `rbinom()`.

**2a.** Initialize two empty matrices. One should have 10 rows and 4 columns, the other should have 10,000 rows and 4 columns. Be sure to give them informative names that follow style guidelines.

**2b.** Separately fill the first column of each matrix with independent draws from a Binomial distribution with probability $0.2$ and $n=5$. Repeat this process for the second through fourth columns using probabilities of $0.4$, $0.6$, and $0.8$, respectively. 

(*Hint: the $n$ in $Bin(n,p)$ notation is not necessarily the same as the `n` in the `rbinom()` function. Read the documentation carefully!*)

**2c.** Use four well-labeled histograms to plot the values of each column (if you want to change the number of bars you can use the `breaks` parameter). Discuss what you see.

**2d.** Calculate the column means of both matrices and present these results in a single table. The rows and columns of your tables should be easy to read and interpret. I suggest using `kableExtra` package.

**2e.** What is the *expected* column mean for each column? Which matrix has observed column means that are closer to this expectation? Why do you think that is?

(*Hint: the expected value of a draw from a $Bin(n,p)$ distribution is $n\times p$*)

**2f.** What is the *expected* variance for the values in each column? Which matrix has observed column sample variances that are closer to these values? Why do you think that is?

(*Hint: the expected value of a draw from a $Bin(n,p)$ distribution is $n\times p\times(1-p)$*)
